--normcome

SELECT
        C.IDCATEGORY as IDCATEGORIA,
        DR.IDDOCUMENT  || ' - ' || DR.NMTITLE as normativa
    FROM
        DCDOCREVISION DR 
	LEFT JOIN
		DCDOCUMENT D
			ON D.CDDOCUMENT = DR.CDDOCUMENT
    LEFT JOIN
        DCCATEGORY C 
            ON C.CDCATEGORY =  DR.CDCATEGORY 
	INNER JOIN
        GNREVISION GR 
            ON GR.CDREVISION=DR.CDREVISION 
    WHERE
        DR.FGCURRENT = 1
		AND D.FGSTATUS = 2
		AND (
		  C.IDCATEGORY = 'D' OR
		  C.IDCATEGORY = 'R' OR
		  C.IDCATEGORY LIKE '1-DAC%' OR
		  C.IDCATEGORY LIKE '2-DGC%' OR
		  C.IDCATEGORY LIKE '3-DR%' OR
		  C.IDCATEGORY LIKE '1-RR%' OR
		  C.IDCATEGORY LIKE '2-RPR%' OR
		  C.IDCATEGORY LIKE '3-RSG%' OR
		  C.IDCATEGORY LIKE '4-RVRA%' OR
		  C.IDCATEGORY LIKE '5-RVRIP%' OR
		  C.IDCATEGORY LIKE '6-RVRVM%' OR
		  C.IDCATEGORY LIKE '7-RVRAF%') 


--cantwf

select count(*) cantidad from wfprocess where cdprocessmodel = 12101 and fgstatus = 1 and idprocess <> :paramIdWf


--idboletitu

SELECT 
LPAD(COUNT(DR.IDDOCUMENT)+1,4,'0') idsecuencial
FROM
        DCDOCREVISION DR 
	LEFT JOIN
		DCDOCUMENT D
			ON D.CDDOCUMENT = DR.CDDOCUMENT
    LEFT JOIN
        DCCATEGORY C 
            ON C.CDCATEGORY =  DR.CDCATEGORY 
			INNER JOIN
    GNREVISION GR 
            ON GR.CDREVISION=DR.CDREVISION 
WHERE D.FGSTATUS = 2
AND C.IDCATEGORY = 'DI-SG-DGI-B'
AND to_char(sysdate, 'YYYY') = to_char(GR.DTREVISION, 'YYYY')
AND to_char(sysdate, 'MM') = to_char(GR.DTREVISION, 'MM')

--cantnormativas

SELECT
        COUNT(GRID.IDENTIFICADOR) cantnorm
    FROM
        WFPROCESS WFP  
    JOIN
        GNASSOCFORMREG REG 
            ON WFP.CDASSOCREG = REG.CDASSOC  
    JOIN
        DYNBOLENORM BOL 
            ON REG.OIDENTITYREG = BOL.OID  
    JOIN
        DYNGRIDBOLENORM GRID 
            ON BOL.OID = GRID.OIDABCXVI3BT4S07ZZ  
    WHERE
        WFP.IDPROCESS=:paraIdWkf
		AND GRID.VALOATRIDOCU = 'incluir'

--normativa

SELECT
        C.IDCATEGORY as IDCATEGORIA,
        C.NMCATEGORY as CATEGORIA,
        DR.IDDOCUMENT as IDDOCUMENTO,
        DR.NMTITLE TITULODOCUMENTO,
		GR.DTREVISION FECHADOCUMENTO,
		CASE WHEN TO_DATE(SYSDATE, 'YYYY-MM-DD') -  TO_DATE(GR.DTREVISION, 'YYYY-MM-DD') <= 7 THEN 'UltimaSemana' 
				   WHEN TO_DATE(SYSDATE, 'YYYY-MM-DD') -  TO_DATE(GR.DTREVISION, 'YYYY-MM-DD') <= 7 THEN 'UltimoMes' 
				   ELSE '' 
	    END as RANGOFECHA,
        'https://softexpert-test.ucsc.cl/se/document/dc_view_document/api_view_document.php?nrdoc='  || DR.iddocument as ENLACE,
        'incluir' INCLUIR,
		1 CANTNORM
    FROM
        DCDOCREVISION DR 
	LEFT JOIN
		DCDOCUMENT D
			ON D.CDDOCUMENT = DR.CDDOCUMENT
    LEFT JOIN
        DCCATEGORY C 
            ON C.CDCATEGORY =  DR.CDCATEGORY 
	INNER JOIN
        GNREVISION GR 
            ON GR.CDREVISION=DR.CDREVISION 
    WHERE
        DR.FGCURRENT = 1
		AND D.FGSTATUS = 2
		AND (
		  C.IDCATEGORY = 'D' OR
		  C.IDCATEGORY = 'R' OR
		  C.IDCATEGORY LIKE '1-DAC%' OR
		  C.IDCATEGORY LIKE '2-DGC%' OR
		  C.IDCATEGORY LIKE '3-DR%' OR
		  C.IDCATEGORY LIKE '1-RR%' OR
		  C.IDCATEGORY LIKE '2-RPR%' OR
		  C.IDCATEGORY LIKE '3-RSG%' OR
		  C.IDCATEGORY LIKE '4-RVRA%' OR
		  C.IDCATEGORY LIKE '5-RVRIP%' OR
		  C.IDCATEGORY LIKE '6-RVRVM%' OR
		  C.IDCATEGORY LIKE '7-RVRAF%') 
	AND EXISTS
	(SELECT
            NMVALUE 
	 FROM
            DCDOCUMENTATTRIB ATT 
        WHERE
            ATT.CDATTRIBUTE=50 
            AND ATT.CDDOCUMENT=DR.CDDOCUMENT 
            AND ATT.CDREVISION=DR.CDREVISION
			AND (ATT.NMVALUE IS NULL OR ATT.NMVALUE = 'excluir' OR ATT.NMVALUE = 'cancelado'))
	AND (GR.DTREVISION >= 
	(SELECT MAX(GR2.DTREVISION)
	FROM DCDOCREVISION DR2
	LEFT JOIN DCDOCUMENT D2 ON D2.CDDOCUMENT = DR2.CDDOCUMENT
	JOIN DCCATEGORY C2 ON C2.CDCATEGORY = DR2.CDCATEGORY
	LEFT JOIN GNREVISION GR2 ON GR2.CDREVISION = DR2.CDREVISION
	WHERE C2.IDCATEGORY = 'DI-SG-DGI-B') OR NOT EXISTS
	(SELECT GR2.DTREVISION
	FROM DCDOCREVISION DR2
	LEFT JOIN DCDOCUMENT D2 ON D2.CDDOCUMENT = DR2.CDDOCUMENT
	JOIN DCCATEGORY C2 ON C2.CDCATEGORY = DR2.CDCATEGORY
	LEFT JOIN GNREVISION GR2 ON GR2.CDREVISION = DR2.CDREVISION
	WHERE C2.IDCATEGORY = 'DI-SG-DGI-B')
		)
	AND NOT EXISTS
	(SELECT GRID.IDENTIFICADOR
	FROM WFPROCESS WFP
	JOIN GNASSOCFORMREG REG ON WFP.CDASSOCREG = REG.CDASSOC
	JOIN DYNBOLENORM BOL ON REG.OIDENTITYREG = BOL.OID
	JOIN DYNGRIDBOLENORM GRID ON BOL.OID = GRID.OIDABCXVI3BT4S07ZZ
	WHERE GRID.IDENTIFICADOR = DR.IDDOCUMENT 
	 AND WFP.IDPROCESS=:paraIdWkf)


